--- # Install Docker
- hosts: lightsail
  become: yes
  tasks:
  - name: Install Docker
    shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh && sudo usermod -aG docker bl